// --------------------------------------
// Lua_Carbuncle
// Carbuncle! At least, his frames
// and animation.
// --------------------------------------
// Frames
rawset(_G, "carbyframes", {})
// CARBY1 Idle
carbyframes[0] = {}
carbyframes[0].frame = 0
carbyframes[0].duration = (TICRATE*170/100)+10
carbyframes[0].endmovement = 0		// How far to move on the x axis after the frame is complete
// CARBY1 Idle (short)
carbyframes[1] = {}
carbyframes[1].frame = 0
carbyframes[1].duration = 2
carbyframes[1].endmovement = 0
// CARBY2 (ears together)
carbyframes[2] = {}
carbyframes[2].frame = 1
carbyframes[2].duration = 2
carbyframes[2].endmovement = 0
// CARBY3 (hands raised)
carbyframes[3] = {}
carbyframes[3].frame = 2
carbyframes[3].duration = 2
carbyframes[3].endmovement = 0
// CARBY4 (match start)
carbyframes[4] = {}
carbyframes[4].frame = 3
carbyframes[4].duration = 2
carbyframes[4].endmovement = 0
// CARBY5
carbyframes[5] = {}
carbyframes[5].frame = 4
carbyframes[5].duration = 5
carbyframes[5].endmovement = 0
// CARBY6
carbyframes[6] = {}
carbyframes[6].frame = 5
carbyframes[6].duration = 3
carbyframes[6].endmovement = 0
// CARBY7
carbyframes[7] = {}
carbyframes[7].frame = 6
carbyframes[7].duration = 3
carbyframes[7].endmovement = 0
// CARBY8
carbyframes[8] = {}
carbyframes[8].frame = 7
carbyframes[8].duration = 3
carbyframes[8].endmovement = 0
// CARBY9
carbyframes[9] = {}
carbyframes[9].frame = 8
carbyframes[9].duration = 7
carbyframes[9].endmovement = 0
// CARBY10
carbyframes[10] = {}
carbyframes[10].frame = 9
carbyframes[10].duration = 4
carbyframes[10].endmovement = 0
// CARBY11
carbyframes[11] = {}
carbyframes[11].frame = 10
carbyframes[11].duration = 2
carbyframes[11].endmovement = 0
// CARBY12
carbyframes[12] = {}
carbyframes[12].frame = 11
carbyframes[12].duration = 10
carbyframes[12].endmovement = 0
// CARBY44 (Side step 1)
carbyframes[13] = {}
carbyframes[13].frame = 43
carbyframes[13].duration = 4
carbyframes[13].endmovement = 0
// CARBY45 (Side step 1)
carbyframes[14] = {}
carbyframes[14].frame = 44
carbyframes[14].duration = 4
carbyframes[14].endmovement = 7
// CARBY19 (Dance left)
carbyframes[15] = {}
carbyframes[15].frame = 18
carbyframes[15].duration = 2
carbyframes[15].endmovement = 0
// CARBY20 (Dance left turn)
carbyframes[16] = {}
carbyframes[16].frame = 19
carbyframes[16].duration = 2
carbyframes[16].endmovement = 0
// CARBY21 (Spin)
carbyframes[17] = {}
carbyframes[17].frame = 20
carbyframes[17].duration = 2
carbyframes[17].endmovement = 0
// CARBY22 (Spin)
carbyframes[18] = {}
carbyframes[18].frame = 21
carbyframes[18].duration = 2
carbyframes[18].endmovement = 0
// CARBY23 (Walk left)
carbyframes[19] = {}
carbyframes[19].frame = 22
carbyframes[19].duration = 2
carbyframes[19].endmovement = 1
// CARBY24 (Walk left)
carbyframes[20] = {}
carbyframes[20].frame = 23
carbyframes[20].duration = 2
carbyframes[20].endmovement = 1
// CARBY25 (Walk left)
carbyframes[21] = {}
carbyframes[21].frame = 24
carbyframes[21].duration = 2
carbyframes[21].endmovement = 1
// CARBY36 (tounge)
carbyframes[22] = {}
carbyframes[22].frame = 35
carbyframes[22].duration = 3
carbyframes[22].endmovement = 0
// CARBY37 (tounge)
carbyframes[23] = {}
carbyframes[23].frame = 36
carbyframes[23].duration = 3
carbyframes[23].endmovement = 0
// CARBY38 (tounge)
carbyframes[24] = {}
carbyframes[24].frame = 37
carbyframes[24].duration = 3
carbyframes[24].endmovement = 0
// CARBY48 (Spin)
carbyframes[25] = {}
carbyframes[25].frame = 47
carbyframes[25].duration = 2
carbyframes[25].endmovement = 0
// CARBY13 (Nutreal)
carbyframes[26] = {}
carbyframes[26].frame = 12
carbyframes[26].duration = 2
carbyframes[26].endmovement = 0
// CARBY14 (Slightly squished)
carbyframes[27] = {}
carbyframes[27].frame = 13
carbyframes[27].duration = 2
carbyframes[27].endmovement = 0
// CARBY39 (Squished)
carbyframes[28] = {}
carbyframes[28].frame = 38
carbyframes[28].duration = 2
carbyframes[28].endmovement = 0
// CARBY40 (Squished)
carbyframes[29] = {}
carbyframes[29].frame = 39
carbyframes[29].duration = 16
carbyframes[29].endmovement = 0
// CARBY15 (After squish)
carbyframes[30] = {}
carbyframes[30].frame = 14
carbyframes[30].duration = 26
carbyframes[30].endmovement = 0
// CARBY15 (Stretch)
carbyframes[31] = {}
carbyframes[31].frame = 14
carbyframes[31].duration = 10
carbyframes[31].endmovement = 0
// CARBY13 (Nutreal) (Long)
carbyframes[32] = {}
carbyframes[32].frame = 12
carbyframes[32].duration = 10
carbyframes[32].endmovement = 0
// CARBY16 (Mouth open)
carbyframes[33] = {}
carbyframes[33].frame = 15
carbyframes[33].duration = 12
carbyframes[33].endmovement = 0
// CARBY17 (Mouth open)
carbyframes[34] = {}
carbyframes[34].frame = 16
carbyframes[34].duration = 12
carbyframes[34].endmovement = 0
// CARBY18 (Mouth open)
carbyframes[35] = {}
carbyframes[35].frame = 17
carbyframes[35].duration = 24
carbyframes[35].endmovement = 0
// CARBY41 (Dance)
carbyframes[36] = {}
carbyframes[36].frame = 40
carbyframes[36].duration = 3
carbyframes[36].endmovement = 0
// CARBY42 (Dance)
carbyframes[37] = {}
carbyframes[37].frame = 41
carbyframes[37].duration = 3
carbyframes[37].endmovement = 0
// CARBY43 (Dance)
carbyframes[38] = {}
carbyframes[38].frame = 42
carbyframes[38].duration = 3
carbyframes[38].endmovement = 0
// CARBY26 (Yawn)
carbyframes[39] = {}
carbyframes[39].frame = 25
carbyframes[39].duration = 3
carbyframes[39].endmovement = 0
// CARBY27 (Yawn)
carbyframes[40] = {}
carbyframes[40].frame = 26
carbyframes[40].duration = 3
carbyframes[40].endmovement = 0
// CARBY28 (Yawn)
carbyframes[41] = {}
carbyframes[41].frame = 27
carbyframes[41].duration = 3
carbyframes[41].endmovement = 0
// CARBY29 (Sleep)
carbyframes[42] = {}
carbyframes[42].frame = 28
carbyframes[42].duration = 13
carbyframes[42].endmovement = 0
// CARBY30 (Sleep)
carbyframes[43] = {}
carbyframes[43].frame = 29
carbyframes[43].duration = 13
carbyframes[43].endmovement = 0
// CARBY31 (Sleep)
carbyframes[44] = {}
carbyframes[44].frame = 30
carbyframes[44].duration = 13
carbyframes[44].endmovement = 0
// CARBY32 (Wake up)
carbyframes[45] = {}
carbyframes[45].frame = 31
carbyframes[45].duration = 3
carbyframes[45].endmovement = 0
// CARBY33 (Wake up)
carbyframes[46] = {}
carbyframes[46].frame = 32
carbyframes[46].duration = 20
carbyframes[46].endmovement = 0
// FBNCL15 (Spin)
carbyframes[47] = {}
carbyframes[47].frame = 14
carbyframes[47].duration = 2
carbyframes[47].endmovement = 0
// FBNCL16 (Spin)
carbyframes[48] = {}
carbyframes[48].frame = 15
carbyframes[48].duration = 2
carbyframes[48].endmovement = 0
// FBNCL17 (Spin)
carbyframes[49] = {}
carbyframes[49].frame = 16
carbyframes[49].duration = 2
carbyframes[49].endmovement = 0
// FBNCL18 (Spin)
carbyframes[50] = {}
carbyframes[50].frame = 17
carbyframes[50].duration = 2
carbyframes[50].endmovement = 0
// Animations
rawset(_G, "carbyanimations", {})
// Idle
carbyanimations[0] = {}
carbyanimations[0].numframes = 17
carbyanimations[0].frames = {}
carbyanimations[0].frames[0] = 0
carbyanimations[0].frames[1] = 3
carbyanimations[0].frames[2] = 1
carbyanimations[0].frames[3] = 3
carbyanimations[0].frames[4] = 0
carbyanimations[0].frames[5] = 3
carbyanimations[0].frames[6] = 1
carbyanimations[0].frames[7] = 3
carbyanimations[0].frames[8] = 0
carbyanimations[0].frames[9] = 2
carbyanimations[0].frames[10] = 1
carbyanimations[0].frames[11] = 2
carbyanimations[0].frames[12] = 1
carbyanimations[0].frames[13] = 2
carbyanimations[0].frames[14] = 0
carbyanimations[0].frames[15] = 3
carbyanimations[0].frames[16] = 1
carbyanimations[0].frames[17] = 3
carbyanimations[0].frames[18] = 0
carbyanimations[0].frames[19] = 2
carbyanimations[0].frames[20] = 1
carbyanimations[0].frames[21] = 2
carbyanimations[0].frames[22] = 1
carbyanimations[0].frames[23] = 2
carbyanimations[0].frames[24] = 2
carbyanimations[0].frames[25] = 0
carbyanimations[0].frames[26] = 3
carbyanimations[0].frames[27] = 1
carbyanimations[0].frames[28] = 3
carbyanimations[0].frames[29] = 0
carbyanimations[0].frames[30] = 0
carbyanimations[0].canflip = false	// If true, when movement is reversed, flip the sprite
carbyanimations[0].nextanim = -1	// 0 or greater = next animation, -1 or less = random animation
// Match start
carbyanimations[1] = {}
carbyanimations[1].numframes = 11
carbyanimations[1].frames = {}
carbyanimations[1].frames[0] = 0
carbyanimations[1].frames[1] = 3
carbyanimations[1].frames[2] = 4
carbyanimations[1].frames[3] = 5
carbyanimations[1].frames[4] = 6
carbyanimations[1].frames[5] = 7
carbyanimations[1].frames[6] = 8
carbyanimations[1].frames[7] = 9
carbyanimations[1].frames[8] = 10
carbyanimations[1].frames[9] = 11
carbyanimations[1].frames[10] = 12
carbyanimations[1].canflip = false
carbyanimations[1].nextanim = 0
// Side step
carbyanimations[2] = {}
carbyanimations[2].numframes = 9
carbyanimations[2].frames = {}
carbyanimations[2].frames[0] = 1
carbyanimations[2].frames[1] = 13
carbyanimations[2].frames[2] = 14
carbyanimations[2].frames[3] = 1
carbyanimations[2].frames[4] = 13
carbyanimations[2].frames[5] = 14
carbyanimations[2].frames[6] = 1
carbyanimations[2].frames[7] = 13
carbyanimations[2].frames[8] = 14
carbyanimations[2].canflip = true
carbyanimations[2].nextanim = 0
// Spin to walk
carbyanimations[3] = {}
carbyanimations[3].numframes = 4
carbyanimations[3].frames = {}
carbyanimations[3].frames[0] = 15
carbyanimations[3].frames[1] = 16
carbyanimations[3].frames[2] = 17
carbyanimations[3].frames[3] = 18
carbyanimations[3].canflip = true
carbyanimations[3].nextanim = 4
// Walk
carbyanimations[4] = {}
carbyanimations[4].numframes = 20
carbyanimations[4].frames = {}
carbyanimations[4].frames[0] = 19
carbyanimations[4].frames[1] = 20
carbyanimations[4].frames[2] = 19
carbyanimations[4].frames[3] = 21
carbyanimations[4].frames[4] = 19
carbyanimations[4].frames[5] = 20
carbyanimations[4].frames[6] = 19
carbyanimations[4].frames[7] = 21
carbyanimations[4].frames[8] = 19
carbyanimations[4].frames[9] = 20
carbyanimations[4].frames[10] = 19
carbyanimations[4].frames[11] = 21
carbyanimations[4].frames[12] = 19
carbyanimations[4].frames[13] = 20
carbyanimations[4].frames[14] = 19
carbyanimations[4].frames[15] = 21
carbyanimations[4].frames[16] = 19
carbyanimations[4].frames[17] = 20
carbyanimations[4].frames[18] = 19
carbyanimations[4].frames[19] = 21
carbyanimations[4].canflip = true
carbyanimations[4].nextanim = 0
// Tounge
carbyanimations[5] = {}
carbyanimations[5].numframes = 8
carbyanimations[5].frames = {}
carbyanimations[5].frames[0] = 22
carbyanimations[5].frames[1] = 23
carbyanimations[5].frames[2] = 24
carbyanimations[5].frames[3] = 23
carbyanimations[5].frames[4] = 24
carbyanimations[5].frames[5] = 23
carbyanimations[5].frames[6] = 24
carbyanimations[5].frames[7] = 22
carbyanimations[5].canflip = false
carbyanimations[5].nextanim = 0
// Spin
carbyanimations[6] = {}
carbyanimations[6].numframes = 14
carbyanimations[6].frames = {}
carbyanimations[6].frames[0] = 17
carbyanimations[6].frames[1] = 18
carbyanimations[6].frames[2] = 25
carbyanimations[6].frames[3] = 26
carbyanimations[6].frames[4] = 17
carbyanimations[6].frames[5] = 18
carbyanimations[6].frames[6] = 25
carbyanimations[6].frames[7] = 26
carbyanimations[6].frames[8] = 15
carbyanimations[6].frames[9] = 16
carbyanimations[6].frames[10] = 16
carbyanimations[6].frames[11] = 16
carbyanimations[6].frames[12] = 16
carbyanimations[6].frames[13] = 15
carbyanimations[6].canflip = false
carbyanimations[6].nextanim = 0
// Squish
carbyanimations[7] = {}
carbyanimations[7].numframes = 8
carbyanimations[7].frames = {}
carbyanimations[7].frames[0] = 26
carbyanimations[7].frames[1] = 27
carbyanimations[7].frames[2] = 28
carbyanimations[7].frames[3] = 29
carbyanimations[7].frames[4] = 28
carbyanimations[7].frames[5] = 27
carbyanimations[7].frames[6] = 26
carbyanimations[7].frames[7] = 30
carbyanimations[7].canflip = false
carbyanimations[7].nextanim = 0
// Stretch
carbyanimations[8] = {}
carbyanimations[8].numframes = 6
carbyanimations[8].frames = {}
carbyanimations[8].frames[0] = 32
carbyanimations[8].frames[1] = 31
carbyanimations[8].frames[2] = 32
carbyanimations[8].frames[3] = 31
carbyanimations[8].frames[4] = 32
carbyanimations[8].frames[5] = 31
carbyanimations[8].canflip = false
carbyanimations[8].nextanim = 0
// Mouth open
carbyanimations[9] = {}
carbyanimations[9].numframes = 5
carbyanimations[9].frames = {}
carbyanimations[9].frames[0] = 33
carbyanimations[9].frames[1] = 34
carbyanimations[9].frames[2] = 35
carbyanimations[9].frames[3] = 34
carbyanimations[9].frames[4] = 33
carbyanimations[9].canflip = false
carbyanimations[9].nextanim = 0
// Dance
carbyanimations[10] = {}
carbyanimations[10].numframes = 10
carbyanimations[10].frames = {}
carbyanimations[10].frames[0] = 36
carbyanimations[10].frames[1] = 37
carbyanimations[10].frames[2] = 38
carbyanimations[10].frames[3] = 37
carbyanimations[10].frames[4] = 38
carbyanimations[10].frames[5] = 37
carbyanimations[10].frames[6] = 38
carbyanimations[10].frames[7] = 37
carbyanimations[10].frames[8] = 38
carbyanimations[10].frames[9] = 37
carbyanimations[10].canflip = false
carbyanimations[10].nextanim = 0
// Yawn
carbyanimations[11] = {}
carbyanimations[11].numframes = 8
carbyanimations[11].frames = {}
carbyanimations[11].frames[0] = 39
carbyanimations[11].frames[1] = 40
carbyanimations[11].frames[2] = 41
carbyanimations[11].frames[3] = 40
carbyanimations[11].frames[4] = 41
carbyanimations[11].frames[5] = 40
carbyanimations[11].frames[6] = 41
carbyanimations[11].frames[7] = 39
carbyanimations[11].canflip = false
carbyanimations[11].nextanim = 12
// Sleep
carbyanimations[12] = {}
carbyanimations[12].numframes = 11
carbyanimations[12].frames = {}
carbyanimations[12].frames[0] = 42
carbyanimations[12].frames[1] = 43
carbyanimations[12].frames[2] = 44
carbyanimations[12].frames[3] = 43
carbyanimations[12].frames[4] = 44
carbyanimations[12].frames[5] = 43
carbyanimations[12].frames[6] = 44
carbyanimations[12].frames[7] = 43
carbyanimations[12].frames[8] = 45
carbyanimations[12].frames[9] = 42
carbyanimations[12].frames[10] = 46
carbyanimations[12].canflip = false
carbyanimations[12].nextanim = 0
// Constant spinning (Fakebuncle leaving)
carbyanimations[13] = {}
carbyanimations[13].numframes = 4
carbyanimations[13].frames = {}
carbyanimations[13].frames[0] = 47
carbyanimations[13].frames[1] = 48
carbyanimations[13].frames[2] = 49
carbyanimations[13].frames[3] = 50
carbyanimations[13].canflip = false
carbyanimations[13].nextanim = 13
// Constant spinning (Carbuncle leaving)
carbyanimations[14] = {}
carbyanimations[14].numframes = 4
carbyanimations[14].frames = {}
carbyanimations[14].frames[0] = 17
carbyanimations[14].frames[1] = 18
carbyanimations[14].frames[2] = 25
carbyanimations[14].frames[3] = 47
carbyanimations[14].canflip = false
carbyanimations[14].nextanim = 14

rawset(_G, "carbyrandomlist", {})
carbyrandomlist[0] = 2
carbyrandomlist[1] = 3
carbyrandomlist[2] = 5
carbyrandomlist[3] = 6
carbyrandomlist[4] = 7
carbyrandomlist[5] = 8
carbyrandomlist[6] = 9
carbyrandomlist[7] = 10
carbyrandomlist[8] = 11
rawset(_G, "carbyrandomlength", 9)
