freeslot(
	"MT_CREDITS_STAR_SPAWNER",

	"MT_CREDITS_TS_BEAM",
	"S_CREDITS_TS_BEAM",
	"SPR_TSBM"
);

mobjinfo[MT_CREDITS_STAR_SPAWNER] = {
	--$Name Credits Star Spawner
	--$Sprite FWRKB0
	--$Category SUGOI Decoration
	doomednum = 3504,
	spawnstate = S_INVISIBLE,
	radius = 21*FRACUNIT,
	height = 42*FRACUNIT,
	flags = MF_NOGRAVITY|MF_NOBLOCKMAP|MF_NOSECTOR|MF_NOCLIP|MF_NOCLIPHEIGHT|MF_NOCLIPTHING|MF_SCENERY
}

/* Don't like it
local STAR_RANGE = 1536;
addHook("MobjThinker", function(mo)
	local add_pos = {
		x = P_RandomRange(-STAR_RANGE, STAR_RANGE) * FRACUNIT,
		y = 0,
		z = P_RandomRange(-STAR_RANGE, STAR_RANGE) * FRACUNIT,
	};

	local star = P_SpawnMobjFromMobj(
		mo,
		add_pos.x, add_pos.y, add_pos.z,
		MT_FIREWORK_SFX
	);

	P_InstaThrust(star, mo.angle, P_RandomRange(1, 128) * (mo.scale / 8));

	star.destscale = P_RandomRange(1, 8) * (mo.destscale / 8);
	P_SetScale(star, star.destscale);

	star.fuse = 60 * TICRATE;
end, MT_CREDITS_STAR_SPAWNER);
*/

mobjinfo[MT_CREDITS_TS_BEAM] = {
	--$Name Credits Teleport Station Beam
	--$Sprite FWRKA0
	--$Category SUGOI Decoration
	doomednum = 3513,
	spawnstate = S_CREDITS_TS_BEAM,
	radius = 21*FRACUNIT,
	height = 42*FRACUNIT,
	flags = MF_NOGRAVITY|MF_NOBLOCKMAP|MF_NOCLIP|MF_NOCLIPHEIGHT|MF_NOCLIPTHING|MF_SCENERY
}

states[S_CREDITS_TS_BEAM] = {SPR_TSBM, A|FF_ADD, -1, nil, 0, 0, S_NULL}

addHook("MobjThinker", function(mo)
	mo.flags2 = $1 ^^ MF2_DONTDRAW;
end, MT_CREDITS_TS_BEAM);

local creditStrings = {
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{"SUGOI TEAM", 0, "header"}, -- string, camera, flags/header/thanks, secret, pic side
	{""},
	{""},
	{"CREDITS", 0, "header"},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{"SUGOI", nil, "header"},
	{""},
	{""},
	{""},
	{""},
	{"MAPA1: Retro Hill Zone, Act 1", 101, V_YELLOWMAP, nil, "R"},
	{"            by Pogofen", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPA2: Hilltop Hunt Zone", 102, V_YELLOWMAP, nil, "L"},
	{"            by Fres", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPA3: Groggy Gale Zone", 103, V_YELLOWMAP, nil, "R"},
	{"            by TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Mountain Journey\"", nil, V_ALLOWLOWERCASE},
	{"    by Supergoose", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPA4: Skytop Zone", 104, V_YELLOWMAP, nil, "L"},
	{"            by Glaber", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Mysticism\" by Necros/PM", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: Drilla by SSNTails", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Lua: toaster, Prime 2.0", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPA5: Concrete Jungle Zone", 105, V_YELLOWMAP, nil, "R"},
	{"            by JStheguy", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPA6: Jello Factory Zone", 106, V_YELLOWMAP, nil, "L"},
	{"            by Mystyc Cheez", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPA7: Quartzite Crag Zone", 107, V_YELLOWMAP, nil, "R"},
	{"            by SeventhSentinel", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPA8: Contaminated Water Zone", 108, V_YELLOWMAP, nil, "L"},
	{"            by LazyMK", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Trip to Blue\"", nil, V_ALLOWLOWERCASE},
	{"    by minomus of DOMU", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SOC: Zippy_Zolton", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPA9: Nightlight Ruins Zone", 109, V_YELLOWMAP, nil, "R"},
	{"            by SteelT", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"16bit brain\" by madbrain", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAA: Robotnik Park Zone", 110, V_YELLOWMAP, nil, "L"},
	{"            by FuriousFox", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Pleasure Castle\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic Adventure", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAB: Aquatic Corridors Zone", 111, V_YELLOWMAP, nil, "R"},
	{"            by Revan", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Waves\" by kid pixel", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAC: Overgrown Castle Zone", 112, V_YELLOWMAP, nil, "L"},
	{"            by Chaobrother", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Fillmore Act-1\" from Actraiser", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAD: Lilac Conservatory Zone", 113, V_YELLOWMAP, nil, "R"},
	{"            by RoyKirbs", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Moonlight Capital (VRC6+FDS)\"", nil, V_ALLOWLOWERCASE},
	{"    by MistSomething", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Secret): \"Real American (MIDI)\"", nil, V_ALLOWLOWERCASE},
	{"    by WrstlCraze", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Kwiin, sphere", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAE-AF: Sunset Ruins Zone", 114, V_YELLOWMAP, nil, "L"},
	{"            by StellarStardust", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 1): \"Neo Green Hill\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 2 Beta", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 2): \"Boss 2\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 3D Blast", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAG: Lavender World Zone", 116, V_YELLOWMAP, nil, "L"},
	{"            by CarlosGamer72", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Jumper\" by Waterflame", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAH: Sky Labyrinth Zone", 117, V_YELLOWMAP, nil, "R"},
	{"            by Tripel the fox", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Act 1\" from Sonic Labyrinth", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Lua: Additional fixes by toaster", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAI: Fiery Volcano Zone", 118, V_YELLOWMAP, nil, "L"},
	{"            by Lactozilla", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Memorydust\" by Codex", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAJ: Mine Maze Zone", 119, V_YELLOWMAP, nil, "R"},
	{"            by RomioTheBadass", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - SOC: Drilla from Glaber's SRB2 The Past", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAK: End of Time", 120, V_YELLOWMAP, nil, "L"},
	{"            by Sapheros", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - SOC: Boss derived from work", nil, V_ALLOWLOWERCASE},
	{"    by Morph and Thompson", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Cutscene): \"void\" by nutcase", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Heaven of Pain\" by MADOKAN", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAL: Cute Ice", 121, V_YELLOWMAP, nil, "R"},
	{"            by Zipper", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"REMNANT\"", nil, V_ALLOWLOWERCASE},
	{"    from Megadimension Neptunia Victory II", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAM-AN: Robotnik Laboratory Zone", 122, V_YELLOWMAP, nil, "L"},
	{"            by Manimi", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 1): \"Mechanical Resonance\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic Adventure", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 2): \"Bullet Station\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic Heroes", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: strikezee", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAO: Fudge Canyon Zone", 124, V_YELLOWMAP, nil, "L"},
	{"            by VAdaPEGA", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Easter Egg): From Soup 0.9", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAP: Orbital Complex Zone", 125, V_YELLOWMAP, nil, "R"},
	{"            by Knux576", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Okta-xy-geen\" by Skaven252", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: sphere", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAQ: Gravity Well Zone", 126, V_YELLOWMAP, nil, "L"},
	{"            by Goldenhog", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Galactical Galaxies\"", nil, V_ALLOWLOWERCASE},
	{"    from Speedy Gonzales in Los", nil, V_ALLOWLOWERCASE},
	{"    Gatos Bandidos", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAR: Kodachrome Void Zone", 127, V_YELLOWMAP, nil, "R"},
	{"            by Boinciel", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Overscan\" by Andreas Bilke", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Inspiration: The Doom level", nil, V_ALLOWLOWERCASE},
	{"    \"Dada\" by Scientist", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Special Thanks: MonsterIestyn", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAS: The Grand Finale", 128, V_YELLOWMAP, nil, "L"},
	{"            by Zipper", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Continuous Hits\"", nil, V_ALLOWLOWERCASE},
	{"    from Megadimension Neptunia Victory II", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"Purple Heart's Theme\"", nil, V_ALLOWLOWERCASE},
	{"    from Hyperdimension Neptunia Re;Birth 3", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Dogoo): \"Game Over\"", nil, V_ALLOWLOWERCASE},
	{"    from Hyperdimension Neptunia Re;Birth", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Special Thanks: Boinciel", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPAT: Garanz Site 16", 129, V_YELLOWMAP, nil, "R"},
	{"            by Boinciel", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Mystic Forest\"", nil, V_ALLOWLOWERCASE},
	{"    from Umineko: When They Cry", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Alt): \"Jungle ~A Lush Load~", nil, V_ALLOWLOWERCASE},
	{"    (MIDI)\" by Stacy Anne Christiansen", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPA0: Teleport Station", 100, V_YELLOWMAP, nil, "L"},
	{"            by TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"bump-n-knock\" by phaser", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{""},
	{""},
	{"SUBARASHII", nil, "header"},
	{""},
	{""},
	{""},
	{""},
	{"MAPB1-B2, MAPB9-BA: Green Flowers Zone", 137, V_YELLOWMAP, nil, "R"},
	{"            by StellarStardust", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 1): \"Green Hills Zone\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 2 8-Bit", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 2): \"Aqua Lake Zone\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 2 8-Bit", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 3): \"Rainy Savannah\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic Drift 2", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 4): \"Boss (GG)\" & \"Boss (MS)\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 2 8-Bit", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Boss (Act 4): Manimi", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: White T.U", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPB3: Holiday House Zone", 139, V_YELLOWMAP, nil, "L"},
	{"            by TexDreemurr/PSI Pikachu", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Snow Mountain\"", nil, V_ALLOWLOWERCASE},
	{"    from Super Mario 64", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: Sapheros", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPB4: Sunlit Cavern Zone", 140, V_YELLOWMAP, nil, "R"},
	{"            by BronsoKip", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPB5: Frozen Valley Zone", 141, V_YELLOWMAP, nil, "L"},
	{"            by Tonic ze Hedgefox", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Butterfly Flew Away\" by TB", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPB6: Steel Valley Zone", 142, V_YELLOWMAP, nil, "R"},
	{"            by Elvin & Revan", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPB7: Holiday Hill Zone", 143, V_YELLOWMAP, nil, "L"},
	{"            by SeventhSentinel", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: VAdaPEGA", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPB8: Bubble Tides Zone", 144, V_YELLOWMAP, nil, "R"},
	{"            by TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Pacific Paradise Zone Act 2\"", nil, V_ALLOWLOWERCASE},
	{"    by SeventhSentinel", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: SeventhSentinel", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBB: Plastic Factory Zone", 147, V_YELLOWMAP, nil, "L"},
	{"            by SteelT", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: From Massmouth", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"crux-mas\" by maniac/crux", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBC: Funky Headquarters Zone", 148, V_YELLOWMAP, nil, "R"},
	{"            by Puppyluvv", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Ritz", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"118 in 64 and 194\" by Reed", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBD: Sapphire Frost Zone", 149, V_YELLOWMAP, nil, "L"},
	{"            by Glaber", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: From SRB2 Christmas", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Lua: Larz T.", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Diamond Dust Zone Act 1\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 3D Blast (Genesis)", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBE: Polluted Polis Zone", 150, V_YELLOWMAP, nil, "R"},
	{"            by a guy", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBF: Night Temple Zone", 151, V_YELLOWMAP, nil, "L"},
	{"            by Manimi", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Bureautique\" by art & ytpmvp0", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"International Karate\"", nil, V_ALLOWLOWERCASE},
	{"    by Whiskeymusic", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBG: Crimson Castle Zone", 152, V_YELLOWMAP, nil, "R"},
	{"            by Elvin", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"The Portals of Chaos\"", nil, V_ALLOWLOWERCASE},
	{"    from Heretic", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Ripped from Heretic and Hexen", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBH: Ice Cap Zone", 153, V_YELLOWMAP, nil, "L"},
	{"            by Chicmunk & SSG3", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Ice Cap Zone Act 1\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic the Hedgehog 3", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBI: Dusty Desert Zone, Act 1", 154, V_YELLOWMAP, nil, "R"},
	{"            by Lilac", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"not fragile\"", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBJ: Abandoned Airbase Zone", 155, V_YELLOWMAP, nil, "L"},
	{"            by ICE", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBK: Magma Peaks Zone", 156, V_YELLOWMAP, nil, "R"},
	{"            by Inferno Drag", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: Boinciel", nil, V_ALLOWLOWERCASE},
	{"    & Chicmunk", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBL: Atlantis", 157, V_YELLOWMAP, nil, "L"},
	{"            by DarkTechno", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"-xTREMELY xECUTABLE-\"", nil, V_ALLOWLOWERCASE},
	{"    by Anders Akerheden", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBM: Snow Summit Zone", 158, V_YELLOWMAP, nil, "R"},
	{"            by SAMMY SWAG", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Diamond Dust Zone Act 1\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 3D Blast (Saturn)", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBN: Twilight Grove Zone", 159, V_YELLOWMAP, nil, "L"},
	{"            by Knux576", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Secret Forest Shrine\"", nil, V_ALLOWLOWERCASE},
	{"    by FearofDark", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBO-BP: Mount Torval Zone", 160, V_YELLOWMAP, nil, "R"},
	{"                  by Boo", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 1): \"Torval - Hoverbike or", nil, V_ALLOWLOWERCASE},
	{"    Bust\" from Ratchet: Deadlocked", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 2): \"Mount Vesuvius\"", nil, V_ALLOWLOWERCASE},
	{"    from Ducktales: Remastered", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBQ: Stone Shuttle Zone", 162, V_YELLOWMAP, nil, "L"},
	{"            by Gunla", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Difficult Fight\"", nil, V_ALLOWLOWERCASE},
	{"    from Live-A-Live", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBR: Mix It All Together ! Zone, Act 1", 163, V_YELLOWMAP, nil, "R"},
	{"            by RomioTheBadass", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"High and Broken (Levitated", nil, V_ALLOWLOWERCASE},
	{"    Ruin)\" from Sonic and the Secret Rings", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBS: Steaming Towers Zone", 164, V_YELLOWMAP, nil, "L"},
	{"            by DirkTheHusky", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Tower to the Skies\" by Lucifer", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBT: Sundial Veld Zone", 165, V_YELLOWMAP, nil, "R"},
	{"            by Wind Takadiyami", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Plant Kingdom Act 1\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic Rush Adventure,", nil, V_ALLOWLOWERCASE},
	{"    ported to .it by SteelT", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: Boinciel", nil, V_ALLOWLOWERCASE},
	{"    & Garrean", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Testing: Enodesix/PIRY & Danieldad2244", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBU: Leaps of Faith Zone", 166, V_YELLOWMAP, nil, "L"},
	{"            by LazyMK", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Stage 2 Boss - Strike Ants\"", nil, V_ALLOWLOWERCASE},
	{"    from Dangerous Seed", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBV: Palace Peaks Zone", 167, V_YELLOWMAP, nil, "R"},
	{"            by Garrean", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Sealed Ground (Gigan Rocks)\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic Riders: Zero Gravity", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBW, MAPC1: Roasted Ravine Zone", 168, V_YELLOWMAP, nil, "L"},
	{"            by Lat' and SAMMY SWAG", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Act 1): \"Great Canyon\"", nil, V_ALLOWLOWERCASE},
	{"    from Pokemon Mystery Dungeon", nil, V_ALLOWLOWERCASE},
	{"    Red/Blue Rescue Team", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"Versus Boss\"", nil, V_ALLOWLOWERCASE},
	{"    from Pokemon Mystery Dungeon", nil, V_ALLOWLOWERCASE},
	{"    Red/Blue Rescue Team", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Pinch): \"Boss Battle\"", nil, V_ALLOWLOWERCASE},
	{"    from Learn With Pokemon:", nil, V_ALLOWLOWERCASE},
	{"    Typing Adventure", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBX: Propulsion Peaks Zone", 169, V_YELLOWMAP, nil, "R"},
	{"            by Inferno Drag", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Mysticism\" by Necros/PM", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: Boinciel", nil, V_ALLOWLOWERCASE},
	{"    & Chicmunk", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Theme: Based off Skytop Zone by Glaber", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBY: Pipes of Green", 170, V_YELLOWMAP, nil, "L"},
	{"            by VAdaPEGA", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPBZ: Empty Sanctum Zone", 171, V_YELLOWMAP, nil, "R"},
	{"            by Chaobrother", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Corridors of Time\"", nil, V_ALLOWLOWERCASE},
	{"    from Chrono Trigger", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPC0: Illumination Aerie Zone", 172, V_YELLOWMAP, nil, "L"},
	{"            by JMRante", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Some piece of jazz\" by Rage", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPC2: Final Tower Zone", 174, V_YELLOWMAP, nil, "R"},
	{"            by TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Adonato\" by MrGamer", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"!!!alchemist2\"", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Ripped/edited from", nil, V_ALLOWLOWERCASE},
	{"    Earthworm Jim & Gunstar Heroes", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Boss HUD: Ripped/edited from", nil, V_ALLOWLOWERCASE},
	{"    JoJo's Bizarre Adventure (Arcade)", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPS1: Greenflower Grove Zone, Act 1", 749, V_YELLOWMAP, nil, "L"},
	{"            by Maximus & Tripel", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Green Grove Zone Act 2\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 3D Blast", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Edited from 2.2 Xmas Textures", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPS2: Tropical Island", 750, V_YELLOWMAP, nil, "R"},
	{"            by Lactozilla", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Emerald Forest\"", nil, V_ALLOWLOWERCASE},
	{"    from Time Dominator 1st", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Results): \"Level Complete\"", nil, V_ALLOWLOWERCASE},
	{"    from Time Dominator 1st", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPS3: A Minesweeper Field", 751, V_YELLOWMAP, nil, "L"},
	{"            by Rapidgame7", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Inspiration: Uh, Minesweeper, dude", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPS4: Unknown Temple, Act 1", 752, V_YELLOWMAP, nil, "R"},
	{"            by Sapheros", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Lua Script: TehRealSalt", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Memories\" from Puyo Puyo", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"Fang the Sniper's Theme\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic Triple Trouble", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPS5: Shade Mountain Zone", 753, V_YELLOWMAP, nil, "L"},
	{"            by Badz", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: VelocitOni", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Castle\" from Jazz Jackrabbit 3", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPS6: Soniguri", 754, V_YELLOWMAP, nil, "R"},
	{"            by Yacker & Root", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: Edit of MotorRoach's FSonic,", nil, V_ALLOWLOWERCASE},
	{"    rips from Sonic & Knuckles", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sound Effects: From SUGURI", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Azure Lake Zone\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic the Hedgehog 3", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"Doomsday Zone\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic & Knuckles", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Made OpenGL compatible by frozenLake", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPS7: Highly Responsive to Hedgehogs", 755, V_YELLOWMAP, nil, "L"},
	{"            by LunarDestroyer", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: Ripped using Anex86", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music: Touhou MIDI Central", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Made OpenGL compatible by frozenLake", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPC3-C5: Star Genesis", 175, V_YELLOWMAP, nil, "R"},
	{"            by altalune", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Lua: altalune", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Lua (Flight): Nev3r", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Lua (Assistance): fickleheart", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sprites (Intruder): toaster", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sprites (Ship, Cracking): TehRealSalt", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sprites (Death): Inazuma", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Level): \"Continuous Hits\"", nil, V_ALLOWLOWERCASE},
	{"    from Megadimension Neptunia Victory II", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Intruder): \"Black Paint\"", nil, V_ALLOWLOWERCASE},
	{"    from Paper Mario: Color Splash", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Take Off): \"Marx's Ambition\"", nil, V_ALLOWLOWERCASE},
	{"    from Kirby Super Star Ultra", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Phase 1): \"vs. Star Dream\"", nil, V_ALLOWLOWERCASE},
	{"    from Kirby: Planet Robobot", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Transition): \"Cutscene - Attack\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic Rush Adventure", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Phase 2): \"Intermezzo Without", nil, V_ALLOWLOWERCASE},
	{"    A Leader\" from Kirby: Planet Robobot", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Phase 3): \"Major Boss Battle\"", nil, V_ALLOWLOWERCASE},
	{"    from Freedom Planet", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPC6: Skyport Albatross Zone", 178, V_YELLOWMAP, nil, "L"},
	{"            by Chromatian", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Enemy Hall (MMX Style)\"", nil, V_ALLOWLOWERCASE},
	{"    by JX444444", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPC7: Saccharine Springs Zone", 179, V_YELLOWMAP, nil, "R"},
	{"            by Lach", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"gall-ha-snar\" by mac_of_doom", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPC8: Deleted Domain Zone", 180, V_YELLOWMAP, nil, "L"},
	{"            by Garrean", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Vibes from past\"", nil, V_ALLOWLOWERCASE},
	{"    by Fegolhuzz / Databrothers", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Levels featured:", nil, V_ALLOWLOWERCASE},
	{""},
	{"     - \"Totem Island\" by Root", nil, V_ALLOWLOWERCASE},
	{""},
	{"     - \"Green Meadow\" by Bluesfire", nil, V_ALLOWLOWERCASE},
	{""},
	{"     - \"Alpine Heights\" by Simsmagic", nil, V_ALLOWLOWERCASE},
	{""},
	{"     - \"Verdant Valley\" by Fres", nil, V_ALLOWLOWERCASE},
	{""},
	{"     - \"Storm Stronghold\" by frozenLake", nil, V_ALLOWLOWERCASE},
	{""},
	{"     - \"Greenflower Caves\" by Potatosack", nil, V_ALLOWLOWERCASE},
	{""},
	{"     - \"Sunset Mine\" by White T.U", nil, V_ALLOWLOWERCASE},
	{""},
	{"     - \"Acid Plant\" by CoatRack", nil, V_ALLOWLOWERCASE},
	{""},
	{"     - \"Disco Foundry\" by Kuja", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPB0: Joestar Manor", 136, V_YELLOWMAP, nil, "R"},
	{"            by TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"The Magic House\"", nil, V_ALLOWLOWERCASE},
	{"    from Final Fantasy VI", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Shop): \"Slashed Prices\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: SeventhSentinel", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{""},
	{""},
	{"KIMOKAWAIII Side A", nil, "header"},
	{""},
	{""},
	{""},
	{""},
	{"MAPD1: Lilac Acreage Zone", 209, V_YELLOWMAP, nil, "R"},
	{"            by RoyKirbs", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Cappy's Stage - Kirby's Block", nil, V_ALLOWLOWERCASE},
	{"    Ball (KDL3 Remix)\" by Pinci", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPD2: Midnight Shores Zone", 210, V_YELLOWMAP, nil, "L"},
	{"            by SteelT", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Starry Beach\" by Robby Coker", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPD3: Oceanside Cave Zone", 211, V_YELLOWMAP, nil, "R"},
	{"            by Rumia1", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Grasslands\"", nil, V_ALLOWLOWERCASE},
	{"    by RedNGreen", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SFX: \"Radio Funk - Sonic OVA", nil, V_ALLOWLOWERCASE},
	{"    Reconstruction\" by MrKingalocious", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Kirby's Dream Land 3", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPD4: Aurora Atoll Zone, Act 3", 212, V_YELLOWMAP, nil, "L"},
	{"            by TehRealSalt & SeventhSentinel", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Pre-fight): \"Interrupted Sleep\"", nil, V_ALLOWLOWERCASE},
	{"    from Kirby Super Star", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"Boss Battle\"", nil, V_ALLOWLOWERCASE},
	{"    from Kirby Super Star", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPD5: Verdant Valley Zone", 213, V_YELLOWMAP, nil, "R"},
	{"            by Fres", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Round 5-2 - Ice Scream\"", nil, V_ALLOWLOWERCASE},
	{"    from Ristar", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Lua: Emerald Hunt Advanced", nil, V_ALLOWLOWERCASE},
	{"    by Latius/ah2190", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SOC: AMT Crawla by Lat'", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPD6: Morning Heights Zone", 214, V_YELLOWMAP, nil, "L"},
	{"            by Firework917", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Mission Briefing\"", nil, V_ALLOWLOWERCASE},
	{"    from Time Trax", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Skybox: .Jazz.", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPD7: Arle Satan Bayoen Zone, Act Tsuu", 215, V_YELLOWMAP, nil, "R"},
	{"            by Tripel the Fox", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Stage 1): \"Theme of Puyo Puyo\"", nil, V_ALLOWLOWERCASE},
	{"    from Puyo Puyo", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Stage 2): \"Area A\"", nil, V_ALLOWLOWERCASE},
	{"    from Puyo Puyo Tsuu", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Stage 3): \"Sticker of Puyo Puyo\"", nil, V_ALLOWLOWERCASE},
	{"    from Puyo Puyo", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Stage 4): \"Last Area\"", nil, V_ALLOWLOWERCASE},
	{"    from Puyo Puyo Tsuu", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Stage 5): \"Final of Puyo Puyo\"", nil, V_ALLOWLOWERCASE},
	{"    from Puyo Puyo", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Warning): \"Warning of Puyo Puyo\"", nil, V_ALLOWLOWERCASE},
	{"    from Puyo Puyo", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Game Over): \"Sorrow of Puyo Puyo\"", nil, V_ALLOWLOWERCASE},
	{"    from Puyo Puyo", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPD8: Scarlet Palace", 216, V_YELLOWMAP, nil, "L"},
	{"            by .Jazz.", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Angel Eyes\" by Velvet", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: LordPotatoSack, VAdaPEGA", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPD9: BoBo the Bouncy Boi", 217, V_YELLOWMAP, nil, "R"},
	{"            by TrustyGun", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"murder\" by Reed Richards", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDA: The Zone", 218, V_YELLOWMAP, nil, "L"},
	{"            by Boinciel", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"electricity\" by Strobo", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDB: Lush Meadow Zone", 219, V_YELLOWMAP, nil, "R"},
	{"            by Flare957", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Evening Star\"", nil, V_ALLOWLOWERCASE},
	{"    from Knuckles Chaotix", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDC: Decrepit Plant Zone", 220, V_YELLOWMAP, nil, "L"},
	{"            by TrustyGun", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Cherry Jam\" by Reed Richards", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDD: Cyber Deton", 221, V_YELLOWMAP, nil, "R"},
	{"            by WellDoneSnake", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Boss\" from Super Bomberman", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDE: Knothole Valley Zone", 222, V_YELLOWMAP, nil, "L"},
	{"            by Wumbo", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Ice World\" from Best Friends", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDF: Redcurrant Brewery", 223, V_YELLOWMAP, nil, "R"},
	{"            by Lactozilla", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDG: Extraterrestrial Ruin Zone", 224, V_YELLOWMAP, nil, "L"},
	{"            by SeventhSentinel", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Twilight Space\" from Super Bonk", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDH: Mr. Triangle The Pizza Delivery Guy", 225, V_YELLOWMAP, nil, "R"},
	{"            by Root & Yacker", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Sunset Hill Zone, Act 2 - Sonic", nil, V_ALLOWLOWERCASE},
	{"    Advance 3 (MIDI)\" by Jace", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"Boss\"", nil, V_ALLOWLOWERCASE},
	{"    from Kirby's Dreamland 3", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDI: Robotnik's Fortress, Act 1", 226, V_YELLOWMAP, nil, "L"},
	{"            by Swift", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Dr. Wily Stage 1-2\"", nil, V_ALLOWLOWERCASE},
	{"    from Mega Man: The Wily Wars", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Sonic Mania", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDJ: Icy Hot Cave Zone, Act 1", 227, V_YELLOWMAP, nil, "R"},
	{"            by Sleeperz", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Round 3-2 - Under Magma\"", nil, V_ALLOWLOWERCASE},
	{"    from Ristar", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: Champ", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDK: Diamond Valley Zone", 228, V_YELLOWMAP, nil, "L"},
	{"            by Badz", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Jazz Castle\"", nil, V_ALLOWLOWERCASE},
	{"    from Jazz Jackrabbit 2", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDL: Pointy Egg", 229, V_YELLOWMAP, nil, "R"},
	{"            by Badz", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Jazz Boss Tune 2\"", nil, V_ALLOWLOWERCASE},
	{"    from Jazz Jackrabbit 2", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDM: Shogun Stronghold Zone", 230, V_YELLOWMAP, nil, "L"},
	{"            by TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Outside Shredder's Hideout\"", nil, V_ALLOWLOWERCASE},
	{"    from Teenage Mutant Ninja Turtles:", nil, V_ALLOWLOWERCASE},
	{"    The Hyperstone Heist", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDN: Submerged Corridors Zone", 231, V_YELLOWMAP, nil, "R"},
	{"            by Q.T.D.", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Meditation\" by ArchAngel", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDO: Green Hill Zone", 232, V_YELLOWMAP, nil, "L"},
	{"            by LJ Sonic", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Green Hill Zone\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic the Hedgehog", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDP: Summit Showdown", 233, V_YELLOWMAP, nil, "R"},
	{"            by TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Onslaught II\"", nil, V_ALLOWLOWERCASE},
	{"    from Marvel vs. Capcom", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Alt): \"Boo Takes Charge\"", nil, V_ALLOWLOWERCASE},
	{"    by ThinkOneMoreTime", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDQ: Pure Rock Zone", 234, V_YELLOWMAP, nil, "L"},
	{"            by Goldenhog", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Main Title Part 2\"", nil, V_ALLOWLOWERCASE},
	{"    from Alien 3 (Genesis)", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDR: Backyard Bother", 235, V_YELLOWMAP, nil, "R"},
	{"            by Sryder & Chromatian", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Special Thanks: TehRealSalt,", nil, V_ALLOWLOWERCASE},
	{"    DrTapeworm, Boinciel, VelocitOni", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Overworld): \"The Magic House\"", nil, V_ALLOWLOWERCASE},
	{"    from Final Fantasy VI", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss Intro): \"Sanctuary", nil, V_ALLOWLOWERCASE},
	{"    Guardian's Challenge\" from Earthbound", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss Start): \"Oncoming Boss\"", nil, V_ALLOWLOWERCASE},
	{"    from Earthbound", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Phase 1): \"Sanctuary Guardian\"", nil, V_ALLOWLOWERCASE},
	{"    from Earthbound", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Phase 2): \"Enraged Ones\"", nil, V_ALLOWLOWERCASE},
	{"    from 7th Dragon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Defeat): \"A Bad Dream\"", nil, V_ALLOWLOWERCASE},
	{"    from Earthbound", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Victory): \"You Defeated", nil, V_ALLOWLOWERCASE},
	{"    the Boss!\" from Earthbound", nil, V_ALLOWLOWERCASE},
	{""},
	{" - In Memory Of: Tyler52", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDS: Amethyst Aqueducts Zone", 236, V_YELLOWMAP, nil, "L"},
	{"            by Ikkarou Tatsuru", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"aquarium\" by awesome", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SOC: Flasher by Glaber", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPDT: Acceleration of Soniguri", 237, V_YELLOWMAP, nil, "R"},
	{"            by Tripel the Fox", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: MotorRoach, Lat'", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SFX: Acceleration of Suguri", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPD0: Gateway Sanctuary Zone", 208, V_YELLOWMAP, nil, "L"},
	{"            by TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Kawaii Sanctuary\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Shop): \"Serenity Shopping\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{""},
	{""},
	{"KIMOKAWAIII Side B", 0, "header"},
	{""},
	{""},
	{""},
	{""},
	{"MAPE1: Mechanical Garden Zone", 245, V_YELLOWMAP, nil, "R"},
	{"            by BronsoKip", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Left Alone\" by MasterMind", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPE2: LJ Sonic", 246, V_YELLOWMAP, nil, "L"},
	{"            by LJ Sonic", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"joes#10\"", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPE3: Confleggator", 247, V_YELLOWMAP, nil, "R"},
	{"            by 742mph", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Act 2 Boss\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic the Hedgehog 3", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: CoatRack", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPE4: Acidic Alpines Zone", 248, V_YELLOWMAP, nil, "L"},
	{"            by Lach", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Additional assistance: fickleheart", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPE5: Magmor Zone", 249, V_YELLOWMAP, nil, "R"},
	{"            by Glaber", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Volcano Valley Zone\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 3D Blast (Genesis)", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPE6: Egg Flambe", 250, V_YELLOWMAP, nil, "L"},
	{"            by Glaber", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Pre-fight): \"Unused Boss\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 3D Blast (Genesis)", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"Boss 1\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 3D Blast (Genesis)", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Pinch): \"Boss 2\"", nil, V_ALLOWLOWERCASE},
	{"    from Sonic 3D Blast (Genesis)", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPE7: Wasted Wayward Zone", 251, V_YELLOWMAP, nil, "R"},
	{"            by PersistantRubine", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Desolation Canyon\"", nil, V_ALLOWLOWERCASE},
	{"    from Wild Guns", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPE8: Glacier Glaze Zone", 252, V_YELLOWMAP, nil, "L"},
	{"            by Snu", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Lorenzen's Soil\"", nil, V_ALLOWLOWERCASE},
	{"    from Earthworm Jim 2 (SNES)", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPE9: Desolate Woods Zone", 253, V_YELLOWMAP, nil, "R"},
	{"            by Manimi & Strike", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Part 1): \"Mission ", nil, V_ALLOWLOWERCASE},
	{"    Acomplished\" [sic]", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Cutscene): \"Treasure Box\"", nil, V_ALLOWLOWERCASE},
	{"    by Farmer", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Part 2): \"Return to Io\"", nil, V_ALLOWLOWERCASE},
	{"    by GraveDigger", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEA: Dark Stabot", 254, V_YELLOWMAP, nil, "L"},
	{"            by Manimi", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"depeche maxi\" by tsc", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Pinch): \"euphoriosion\" by tkg", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEB: Nova Shore Zone", 255, V_YELLOWMAP, nil, "R"},
	{"            by DrTapeworm", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"dream in blue water\" by 4mat", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEC: Raspberry Desert Zone", 256, V_YELLOWMAP, nil, "L"},
	{"            by Revan", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"desert dream\" by laxity/kefrens", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Sonic Mania, cesar993,", nil, V_ALLOWLOWERCASE},
	{"    DanielMania123", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPED: Bio Satellite Zone", 257, V_YELLOWMAP, nil, "R"},
	{"            by Chaobrother", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Millennium\" by Sidewinder", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEF: Egg Lasershow", 258, V_YELLOWMAP, nil, "L"},
	{"            by Chaobrother", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"kalomie\" by toady", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEG: Quandary Canyon Zone", 259, V_YELLOWMAP, nil, "R"},
	{"            by RomioTheBadass", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Stage 1-1 (Desert)\"", nil, V_ALLOWLOWERCASE},
	{"    from Ranger-X", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Secret): \"Camel Jazz\"", nil, V_ALLOWLOWERCASE},
	{"    from Aladdin (Genesis)", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Dolphman", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEH: Ruby Castle Zone", 260, V_YELLOWMAP, nil, "L"},
	{"            by Shiron", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Funeral\" by Mick Rippon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Secret): \"Emperor At Work 8:11\"", nil, V_ALLOWLOWERCASE},
	{"    by KurtZ", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Castlevania, Paper Mario,", nil, V_ALLOWLOWERCASE},
	{"    Kingdom Hearts, Sonic Heroes,", nil, V_ALLOWLOWERCASE},
	{"    Cho Aniki", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEI: Sleeping Egg Zone", 261, V_YELLOWMAP, nil, "R"},
	{"            by Nintensis", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Textures: FearsomeFang", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Lua: Pogo Spring originally by Lat',", nil, V_ALLOWLOWERCASE},
	{"    remade by TehRealSalt", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEJ: Dimension Disaster Zone", 262, V_YELLOWMAP, nil, "L"},
	{"            by Lat'", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"YO-KAI Disco\"", nil, V_ALLOWLOWERCASE},
	{"    from Mamorukun Curse!", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Sonic 2, Sonic Mania", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: MotorRoach", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEK: Doomsday Disaster Zone", 263, V_YELLOWMAP, nil, "R"},
	{"            by Lat'", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Phase 1): \"Super Hero\"", nil, V_ALLOWLOWERCASE},
	{"    from Mamorukun Curse!", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Phase 2): \"Mantra\"", nil, V_ALLOWLOWERCASE},
	{"    from Mamorukun Curse!", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Phase 3): \"Ultimate Terror\"", nil, V_ALLOWLOWERCASE},
	{"    from Mamorukun Curse!", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SFX: Pokemon, Angel Beats", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEL: Sunken Shafts Zone", 264, V_YELLOWMAP, nil, "L"},
	{"            by Inferno Dragon", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Mineshaft Tavern\"", nil, V_ALLOWLOWERCASE},
	{"    by stinkbug", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEM: Azure Paradise Zone", 265, V_YELLOWMAP, nil, "R"},
	{"            by LazyMK", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"funky trousers\" by vim!", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEN: Cosmic Valley Zone", 266, V_YELLOWMAP, nil, "L"},
	{"            by davee0", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"tragical song\"", nil, V_ALLOWLOWERCASE},
	{"    by FLYER/R-Age/Psycho", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Textures: Nev3r", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEO: True Protagonist", 267, V_YELLOWMAP, nil, "R"},
	{"            by Goldenhog", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Last Boss\"", nil, V_ALLOWLOWERCASE},
	{"    from Magical Taruruuto-Kun", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Sprites: Megaman 8, Prinny,", nil, V_ALLOWLOWERCASE},
	{"    Makai Kingdom", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SFX: Megaman 8", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEO: Long Journey's End", 268, V_YELLOWMAP, nil, "L"},
	{"            by multiple authors", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Boundless Remorse\"", nil, V_ALLOWLOWERCASE},
	{"     by Blowitch, +TEK", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Alt): \"Last Area - Puyo Puyo Tsuu", nil, V_ALLOWLOWERCASE},
	{"     (FM Cover)\" by Blowitch", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Intermission segments: TehRealSalt", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Level segments contributed by:", nil, V_ALLOWLOWERCASE},
	{""},
	{"    - Room 1: Revan", nil, V_ALLOWLOWERCASE},
	{"    - Room 2: SteelT", nil, V_ALLOWLOWERCASE},
	{"    - Room 3: VAdaPEGA", nil, V_ALLOWLOWERCASE},
	{"    - Room 4: ICE", nil, V_ALLOWLOWERCASE},
	{"    - Room 5: Rumia1", nil, V_ALLOWLOWERCASE},
	{"    - Room 6: .Jazz.", nil, V_ALLOWLOWERCASE},
	{"    - Room 7: TrustyGun", nil, V_ALLOWLOWERCASE},
	{"    - Room 8: RoyKirbs", nil, V_ALLOWLOWERCASE},
	{"    - Room 9: Manimi", nil, V_ALLOWLOWERCASE},
	{"    - Room 10: Glaber", nil, V_ALLOWLOWERCASE},
	{"    - Room 11: DrTapeworm", nil, V_ALLOWLOWERCASE},
	{"    - Room 12: Zipper", nil, V_ALLOWLOWERCASE},
	{"    - Room 13: LJSonic", nil, V_ALLOWLOWERCASE},
	{"    - Room 14: Wumbo", nil, V_ALLOWLOWERCASE},
	{"    - Room 15: Q.T.D.", nil, V_ALLOWLOWERCASE},
	{"    - Room 16: Badz", nil, V_ALLOWLOWERCASE},
	{"    - Room 17: LazyMK", nil, V_ALLOWLOWERCASE},
	{"    - Room 18: Garrean", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPEP: One Last Goodbye", 269, V_YELLOWMAP, nil, "R"},
	{"            by Lach & TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music (Level): \"Celestial Serenade\"", nil, V_ALLOWLOWERCASE},
	{"    by Lach", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Boss): \"Shadow Showdown\"", nil, V_ALLOWLOWERCASE},
	{"    by Lach", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Inspiration: toaster", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"MAPE0: Gateway Dimension Zone", 244, V_YELLOWMAP, nil, "L"},
	{"            by TehRealSalt", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Music: \"Kimoi Dimension\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Music (Shop): \"Whatcha Buying\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Skybox: sphere", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{""},
	{""},
	{"Additional Credits", 0, "header"},
	{""},
	{""},
	{""},
	{""},
	{"FreeDoom textures: FreeDoom team", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - Ported to SRB2 by ShadowHog", nil, V_ALLOWLOWERCASE},
	{""},
	{" - FreeDoom's full credits & license are", nil, V_ALLOWLOWERCASE},
	{"    included in FCREDITS.txt & FCOPYING.txt", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"\130Combine Ring:\128 Lach", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"\130Axis2D:\128 altalune, fickleheart", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"Finale Extra Reel segments (in order):", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - HyperFlare957", nil, V_ALLOWLOWERCASE},
	{" - Chicmunk", nil, V_ALLOWLOWERCASE},
	{" - Chaobrother", nil, V_ALLOWLOWERCASE},
	{" - Nintensis", nil, V_ALLOWLOWERCASE},
	{" - BronsoKip", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"\130Cutscenes:\128 Boinciel & TehRealSalt", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SUGOI, Reveal: \"Hellraiser", nil, V_ALLOWLOWERCASE},
	{"    ~The Mastermind Behind The Scheme~\"", nil, V_ALLOWLOWERCASE},
	{"    from Megadimension Neptunia Victory II", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SUBARASHII, Intro Happy:", nil, V_ALLOWLOWERCASE},
	{"    \"Misato's Theme - Neon Genesis", nil, V_ALLOWLOWERCASE},
	{"    Evangelion (XM)\" by Veritas", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SUBARASHII, Intro Dark:", nil, V_ALLOWLOWERCASE},
	{"    \"Attack On Dogma - Neon Genesis", nil, V_ALLOWLOWERCASE},
	{"    Evangelion (IT)\" by Veritas", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SUBARASHII, Eggman:", nil, V_ALLOWLOWERCASE},
	{"    \"Egg Switch\" from Sonic's Gameworld", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SUBARASHII, Victory:", nil, V_ALLOWLOWERCASE},
	{"    \"You Win\" from Sonic's Gameworld", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SUBARASHII, Secret Intro:", nil, V_ALLOWLOWERCASE},
	{"     \"Game Over\" from Ristar", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SUBARASHII, Contemplation:", nil, V_ALLOWLOWERCASE},
	{"    \"s0ftdrink 0verdose\" by Okeanos", nil, V_ALLOWLOWERCASE},
	{""},
	{" - SUBARASHII, Death:", nil, V_ALLOWLOWERCASE},
	{"    \"Dream Over\" from Sonic Shuffle", nil, V_ALLOWLOWERCASE},
	{""},
	{" - KIMOKAWAIII, Masked Eggman:", nil, V_ALLOWLOWERCASE},
	{"    \"The Hallow Palace\" by Blowitch", nil, V_ALLOWLOWERCASE},
	{""},
	{" - KIMOKAWAIII, Egg Gundam Intro:", nil, V_ALLOWLOWERCASE},
	{"    \"Boss Introduction\"", nil, V_ALLOWLOWERCASE},
	{"    from Marvel vs Capcom", nil, V_ALLOWLOWERCASE},
	{""},
	{" - KIMOKAWAIII, Side A Ending:", nil, V_ALLOWLOWERCASE},
	{"    \"Ending B\" from Puyo Puyo Tsuu", nil, V_ALLOWLOWERCASE},
	{""},
	{" - KIMOKAWAIII, Black Hole:", nil, V_ALLOWLOWERCASE},
	{"    \"Big Boss Confrontation 2\"", nil, V_ALLOWLOWERCASE},
	{"    from Super Metroid", nil, V_ALLOWLOWERCASE},
	{""},
	{" - KIMOKAWAIII, Side B Intro:", nil, V_ALLOWLOWERCASE},
	{"    \"The Other Dimension\" by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"Additional Music:", nil, V_ALLOWLOWERCASE|V_YELLOWMAP},
	{""},
	{" - Title Screen (Scary): \"Dracula Battle\"", nil, V_ALLOWLOWERCASE},
	{"    from Super Castlevania IV", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Title Screen: \"KIMOKAWAIII\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Record Attack: \"Warming Up\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Character Select: \"Starting Out\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Invincibility: \"Sparkle Power\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Super Sneakers: \"Faster, Faster!\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Super Form: \"Feeling Like A Superstar\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Level Clear: \"Sugoi Victory\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Drowning: \"You're Drowning!\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Game Over: \"You've Let Us Down\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Continue: \"Continue? Try Again?\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{" - Credits: \"Fillin' The Room With Cuteness\"", nil, V_ALLOWLOWERCASE},
	{"    by AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{"Special Thanks:", nil, V_YELLOWMAP|V_ALLOWLOWERCASE},
	{""},
	{" - MonsterIestyn", nil, V_ALLOWLOWERCASE},
	{" - Sryder", nil, V_ALLOWLOWERCASE},
	{" - Lach", nil, V_ALLOWLOWERCASE},
	{" - Jeck Jims", nil, V_ALLOWLOWERCASE},
	{" - Larz T.", nil, V_ALLOWLOWERCASE},
	{" - AxelMoon", nil, V_ALLOWLOWERCASE},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{"From the very bottom", 0, "center"},
	{"of my heart, I express", 0, "center"},
	{"my gratitude towards anyone", 0, "center"},
	{"who has ever contributed,", 0, "center"},
	{"played, or even just looked", 0, "center"},
	{"at this silly mod.", 0, "center"},
	{""},
	{"I never expected it to", 0, "center"},
	{"transform into something", 0, "center"},
	{"so huge and amazing.", 0, "center"},
	{""},
	{"Thank you for playing.", 0, "center"},
	{"- TehRealSalt", 0, "center"},
	{""},
	{""},
	{"SUGOI Project", 0, "center"},
	{"2016 - 2024", 0, "center"},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{""},
	{"The End", nil, "header"}
};

-- Container for credits animation variables
sugoi.creditsData = {
	time = 0,
	day = 0,
	fade = NUMTRANSMAPS,
	fadeout = false,
	camera = nil,
};
-- creditStrings, compiled based on what's been unlocked or not
sugoi.creditsCompiled = {};

function sugoi.CompileCredits()
	for _,v in ipairs(creditStrings) do
		local lock = v[4];
		if (lock != nil and not sugoi.Unlocked[lock])
			continue;
		end
		table.insert(sugoi.creditsCompiled, v);
	end

	local pal = mapheaderinfo[gamemap].palette;
	if (sugoi.dayCycles[pal].sky)
		P_SetupLevelSky(sugoi.dayCycles[pal].sky);
	end
end

local CREDITS_HEIGHT = 1408 * FRACUNIT;

function sugoi.CreditsThinker()
	if not (sugoi.creditsCompiled and sugoi.creditsCompiled[1])
		return;
	end

	local pal = mapheaderinfo[gamemap].palette;
	local numcycles = sugoi.dayCycles[pal].cycles;

	if not (sugoi.creditsData) -- for safety
		sugoi.creditsData = {
			time = 0,
			day = 0,
			fade = NUMTRANSMAPS,
			fadeout = false,
			camera = nil,
		};
	end

	if (sugoi.creditsData.camera == nil)
		for mt in mapthings.iterate do
			if (mt.type == mobjinfo[MT_ALTVIEWMAN].doomednum)
			and (mt.mobj and mt.mobj.valid)
				sugoi.creditsData.camera = mt.mobj;
				break;
			end
		end
	end

	local prevtime = sugoi.creditsData.time;
	sugoi.creditsData.time = $1 + 1;

	if (server.cmd.buttons & BT_JUMP) sugoi.creditsData.time = $1 + (TICRATE/2); end -- Faster
	if (server.cmd.buttons & BT_USE) sugoi.creditsData.time = $1 + (TICRATE/2); end -- Faster!
	if (server.cmd.buttons & BT_JUMP and server.cmd.buttons & BT_USE) sugoi.creditsData.time = $1 + (TICRATE/2); end -- FASTER!!

	local length = #sugoi.creditsCompiled;
	local totaltime = (length * 16) - 216 + 24;

	if (numcycles)
		local cycletime = totaltime / numcycles;
		local destdaycycle = (sugoi.creditsData.time / cycletime);

		if (sugoi.creditsData.fadeout)
			if (sugoi.creditsData.fade < NUMTRANSMAPS)
				sugoi.creditsData.fade = $1 + 1;
			elseif (destdaycycle < numcycles)
				sugoi.creditsData.day = destdaycycle;

				if (sugoi.dayCycles[pal].sky)
					P_SetupLevelSky(sugoi.dayCycles[pal].sky + sugoi.creditsData.day);
				end

				sugoi.creditsData.fadeout = false;
			end
		else
			if (sugoi.creditsData.day != destdaycycle)
				sugoi.creditsData.fadeout = true;
			elseif (sugoi.creditsData.fade > 0)
				sugoi.creditsData.fade = $1 - 1;
			end
		end

		if (sugoi.clientrenderer == "software")
		and (sugoi.creditsData.time < totaltime)
			for p in players.iterate do
				P_FlashPal(p, 6 + sugoi.creditsData.day, 2);
			end
		end
	end

	local timeleft = totaltime - sugoi.creditsData.time;

	if (sugoi.creditsData.camera and sugoi.creditsData.camera.valid)
		if (sugoi.creditsData.camera.defaultZ == nil)
			sugoi.creditsData.camera.defaultZ = sugoi.creditsData.camera.z;
		end

		local t = 0;
		if (timeleft > 0)
			t = FixedDiv(timeleft, totaltime);
		end

		local zHeight = ease.inoutsine(t, 0, CREDITS_HEIGHT);

		sugoi.creditsData.camera.z = sugoi.creditsData.camera.defaultZ + zHeight;
	end

	local fademustime = totaltime - (8*TICRATE);
	if (sugoi.creditsData.time >= fademustime and prevtime < fademustime)
		S_FadeOutStopMusic(15*MUSICRATE);
	end

	local endtime = totaltime + (8*TICRATE);
	if (sugoi.creditsData.time >= endtime)
		S_FadeOutStopMusic(MUSICRATE); -- skipping, so fade out the music fast
		sugoi.ExitLevel(nil, 2);
	end
end
